Fitness functions tests
jerzywilczek/emas_rs pull request #10
Opened 2022-12-04 21:44 UTC by stlenyk

Add rosenbrock fn to predefined fitness fn
Add unit tests for rastrigin and rosenbrock

2022-12-05 17:30 UTC, michall-m commented on src/fitness_functions.rs
> +struct AckleyFitneess<const N: usize> {}
double e in Fitness

2022-12-05 17:30 UTC, michall-m commented on src/fitness_functions.rs
> +impl<const N: usize> FitnessFn<N> for AckleyFitneess<N> {
```suggestion
impl<const N: usize> FitnessFn<N> for AckleyFitness<N> {
```

2022-12-05 22:04 UTC, michall-m approved these changes

2022-12-06 20:48 UTC, jerzywilczek requested changes

2022-12-06 20:48 UTC, jerzywilczek commented on Cargo.toml
> +assert_approx_eq = "1.1.0"
If this is only used for testing you should put it in `dev-dependencies` instead.

2022-12-06 21:19 UTC, merged